version: '3'

services:
  client:
    build: ./portfolio
    expose:
      - 3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: always
    volumes:
      - ./portfolio/src:/srv/app/client/src
      - ./portfolio/public:/srv/app/client/public
    command: 'npm run start:client'

  server:
    build: ./server
    expose:
      - 3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./server:/srv/app/server
      - /srv/app/server/node_modules/
    restart: always
    command: 'npm run start:server'

  db:
    container_name: portfolio_mongo
    image: nonoroazoro/rpi-mongo:latest
    expose:
      - '27017'
    restart: always

  proxy:
    container_name: portfolio_proxy
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
      - '27017:27017'
    restart: always

    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/certs:/etc/nginx/certs
