version: '3'

services:

 client:
  build: ./portfolio
  expose: 
    - 3000
  ports: 
    - 3000:3000
  environment:
    - CHOKIDAR_USEPOLLING=true
  volumes: 
    - ./portfolio/src:/srv/app/client/src
    - ./portfolio/public:/srv/app/client/public
  command: "npm run start:client"