version: "3"

services:
  client:
    build: ./portfolio
    expose:
      - 3000
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: always
    volumes:
      - ./portfolio/src:/srv/app/client/src
      - ./portfolio/public:/srv/app/client/public
    command: "npm run start:client"

  server:
    build: ./server
    expose:
      - 5000
    ports:
      - 5000:5000
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./server:/srv/app/server
    restart: always
    command: "npm run start:server"

  db:
    container_name: portfolio_mongo
    image: mongo:latest
    expose:
      - "27017"
    restart: always
